name: Publish NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Set version
        run: |
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else

            echo "VERSION=0.0.0-test" >> $GITHUB_ENV


          fi
      - name: Pack
        run: |
          dotnet pack Synthea.Cli/Synthea.Cli.csproj -c Release -o artifacts \
            /p:ContinuousIntegrationBuild=true /p:PackageVersion=${{ env.VERSION }}
      - name: Push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
